<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>es.mjusticia.corium</groupId>
    <artifactId>corium-dependencies</artifactId>
    <version>${revision}</version>
  </parent>
  <artifactId>corium-playwright-dependencies</artifactId>
  <version>${revision}</version>
  <packaging>pom</packaging>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>es.mjusticia.corium</groupId>
        <artifactId>corium-playwright-bom</artifactId>
        <version>${revision}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-params</artifactId>
    </dependency>
    <dependency>
      <groupId>org.junit.platform</groupId>
      <artifactId>junit-platform-launcher</artifactId>
    </dependency>
    <dependency>
      <groupId>com.microsoft.playwright</groupId>
      <artifactId>playwright</artifactId>
    </dependency>
    <dependency>
      <groupId>com.deque.html.axe-core</groupId>
      <artifactId>playwright</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
    </dependency>
  </dependencies>
  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>${maven.surefire.plugin.version}</version>
          <configuration>
            <properties>
              <configurationParameters>
                junit.jupiter.execution.parallel.enabled=true
                junit.jupiter.execution.parallel.mode.default=concurrent
                junit.jupiter.execution.parallel.config.fixed.parallelism=2
                junit.jupiter.extensions.autodetection.enabled=true
                junit.jupiter.testinstance.lifecycle.default=per_class
              </configurationParameters>
            </properties>
            <systemPropertyVariables>
              <playwright.start>${playwright.start}</playwright.start>
              <playwright.debug>${playwright.debug}</playwright.debug>
              <playwright.start.mobile>${playwright.start.mobile}</playwright.start.mobile>
              <playwright.clear.cache>${playwright.clear.cache}</playwright.clear.cache>
              <playwright.default.timeout>${playwright.default.timeout}</playwright.default.timeout>
              <playwright.headless.driver>${playwright.headless.driver}</playwright.headless.driver>
              <playwright.browser.driver>${playwright.browser.driver}</playwright.browser.driver>
              <playwright.disable.devtools>${playwright.disable.devtools}</playwright.disable.devtools>
              <playwright.proxy.on>${playwright.proxy.on}</playwright.proxy.on>
              <playwright.firefox.proxy.type>${playwright.firefox.proxy.type}</playwright.firefox.proxy.type>
              <playwright.proxy.host>${playwright.proxy.host}</playwright.proxy.host>
              <playwright.proxy.port>${playwright.proxy.port}</playwright.proxy.port>
              <playwright.non.proxy.hosts>${playwright.non.proxy.hosts}</playwright.non.proxy.hosts>
              <playwright.screenshot.on.finish>${playwright.screenshot.on.finish}</playwright.screenshot.on.finish>
              <playwright.tracing.enable>${playwright.tracing.enable}</playwright.tracing.enable>
              <playwright.video.recording>${playwright.video.recording}</playwright.video.recording>
              <playwright.client.cert.pem>${playwright.client.cert.pem}</playwright.client.cert.pem>
              <playwright.client.cert.path.pem>${playwright.client.cert.path.pem}</playwright.client.cert.path.pem>
              <playwright.client.cert.key.pem>${playwright.client.cert.key.pem}</playwright.client.cert.key.pem>
              <playwright.client.cert.origin.pem>${playwright.client.cert.origin.pem}</playwright.client.cert.origin.pem>
              <api.truststore.skip.certificates>${api.truststore.skip.certificates}</api.truststore.skip.certificates>
              <api.disable.host.name.verification>${api.disable.host.name.verification}</api.disable.host.name.verification>
              <api.connect.timeout>${api.connect.timeout}</api.connect.timeout>
              <api.truststore.path.file>${api.truststore.path.file}</api.truststore.path.file>
              <api.truststore.path.file.password>${api.truststore.path.file.password}</api.truststore.path.file.password>
              <jenkins.username>${jenkins.username}</jenkins.username>
              <jenkins.password>${jenkins.password}</jenkins.password>
              <jenkins.host>${jenkins.host}</jenkins.host>
            </systemPropertyVariables>
            <environmentVariables>
              <PWDEBUG>${playwright.debug}</PWDEBUG>
            </environmentVariables>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
