package corium.playwright.path;

public class CoriumPathManager {

    /**
     * The path to the directory containing test output logs, reports, screenshots, etc.
     * This directory holds all logs generated by the tests.
     */
    private static final String TEST_OUTPUT_PATH = "test-output/";

    /**
     * Directory names for different test outcomes.
     */
    private static final String FAILURE_NAME = "failure/",
            SKIPPED_NAME = "skipped/",
            PASSED_NAME = "passed/",
            NOT_DEFINED_NAME = "notdefined/";

    /**
     * Paths for various test output directories.
     */
    private static final String PATH_REPORTER = TEST_OUTPUT_PATH + "reporter/",
            PATH_SCREENSHOTS = TEST_OUTPUT_PATH + "screenshots/",
            PATH_PASSED = PATH_SCREENSHOTS + PASSED_NAME,
            PATH_SKIPPED = PATH_SCREENSHOTS + SKIPPED_NAME,
            PATH_FAILURE = PATH_SCREENSHOTS + FAILURE_NAME,
            PATH_SCREENSHOT_NOT_DEFINED = PATH_SCREENSHOTS + NOT_DEFINED_NAME,
            PATH_DOWNLOADS = TEST_OUTPUT_PATH + "downloads/",
            PATH_LOGS = TEST_OUTPUT_PATH + "logs/",
            PATH_TRACE = TEST_OUTPUT_PATH + "trace/",
            PATH_VIDEOS = TEST_OUTPUT_PATH + "videos/";

    public static String getTestOutputPath() {
        return TEST_OUTPUT_PATH;
    }

    public static String getReporterPath() {
        return PATH_REPORTER;
    }

    public static String getScreenshotsPath() {
        return PATH_SCREENSHOTS;
    }

    public static String getPassedPath() {
        return PATH_PASSED;
    }

    public static String getSkippedPath() {
        return PATH_SKIPPED;
    }

    public static String getFailurePath() {
        return PATH_FAILURE;
    }

    public static String getNotDefinedPath() {
        return PATH_SCREENSHOT_NOT_DEFINED;
    }

    public static String getDownloadsPath() {
        return PATH_DOWNLOADS;
    }

    public static String getLogsPath() {
        return PATH_LOGS;
    }

    public static String getTracePath() {
        return PATH_TRACE;
    }

    public static String getVideosPath() {
        return PATH_VIDEOS;
    }
}
