directorioInforme=informe1
plantilla=plantilla.html
versionAplicacion=2.5.0.0
nombreAplicacion=Certape
logoEncabezado=ImagenMinisterio.png
logoPiePagina=ImagenMinisterio.png
paginaInicio=https://vicalbaltico01.mjusticia.es/certape/clave/InicioSede
navegador=firefox
driverChrome=C:/Z/eclipse-workspace/ministerio/Accesibilidad7/drivers/chromedriver.exe
driverFireFox=C:/Z/eclipse-workspace/ministerio/Accesibilidad7/drivers/geckodriver.exe