Fix all of the following:=Corrige todos los siguientes:
Fix any of the following:=Corrige cualquiera de los siguientes:
Element does not have sufficient color contrast=El elemento no tiene suficiente contraste de color
Element has insufficient color contrast of=El elemento tiene un contraste de color insuficiente de
Images must have alternate text=Las imágenes deben tener texto alternativo
Ensure links have discernible text=Asegúrate de que los enlaces tengan texto discernible
Form elements must have labels=Los elementos de formulario deben tener etiquetas
Expected contrast ratio of 4.5:1=Se espera una relación de contraste de 4.5:1
Form element has explicit <label> that is hidden=El elemento de formulario tiene una etiqueta <label> oculta
List item does not have a <ul>, <ol> or role="list" parent element=El elemento de lista no tiene un padre <ul>, <ol> o role="list"
Some page content is not contained by landmarks=Parte del contenido de la página no está contenido en landmarks
Element is in tab order and does not have accessible text=El elemento está en el orden de tabulación y no tiene texto accesible
Invalid ARIA attribute name=Nombre de atributo ARIA inválido
Invalid ARIA attribute value=Valor de atributo ARIA inválido
Document has multiple static elements with the same id attribute=El documento tiene múltiples elementos estáticos con el mismo atributo id
Page does not have a main landmark=La página no tiene un landmark principal
Role must be one of the valid ARIA roles=El rol debe ser uno de los roles ARIA válidos
The role used is not widely supported in assistive technologies=El rol usado no está ampliamente soportado en tecnologías asistivas
Heading order invalid=Orden de encabezados inválido
role banner is not allowed for given element=El rol banner no está permitido para el elemento dado
Document does not have a non-empty <title> element=El documento no tiene un elemento <title> no vacío
Document has multiple elements referenced with ARIA with the same id attribute=El documento tiene múltiples elementos referenciados con ARIA con el mismo atributo id
Document has more than one banner landmark=El documento tiene más de un landmark de tipo banner
Page must have a level-one heading=La página debe tener un encabezado de nivel uno
Value of lang attribute not included in the list of valid languages=El valor del atributo lang no está incluido en la lista de idiomas válidos