extent.reporter.avent.start=false
extent.reporter.bdd.start=false
extent.reporter.cards.start=false
extent.reporter.email.start=false
extent.reporter.html.start=true
extent.reporter.klov.start=false
extent.reporter.logger.start=true

extent.reporter.spark.out=test-output/reporter/Spark.html

#Screenshot
screenshot.rel.path=test-output/screenshots/

#PDF Report
extent.reporter.pdf.start=true
extent.reporter.pdf.out=test-output/reporter/extent.pdf

#HTML Report
extent.reporter.html.out=test-output/reporter/extent.html

#Logger Logs
extent.reporter.logger.out=test-output/logs/