<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>es.mjusticia.corium</groupId>
  <artifactId>corium-root</artifactId>
  <version>${revision}</version>
  <packaging>pom</packaging>
  <developers>
    <developer>
      <name>Paul Ibanez Raad</name>
    </developer>
  </developers>
  <modules>
    <module>corium-dependencies</module>
    <module>corium-framework</module>
    <module>corium-starters</module>
    <module>corium-bom</module>
  </modules>
  <properties>
    <!-- Configuración del proyecto -->
    <maven.compiler.release>11</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <revision>1.1.0.0</revision>
    <!-- Versiones de dependencias -->
    <commons-io.version>2.18.0</commons-io.version>
    <org.slf4.version>2.0.16</org.slf4.version>
    <com.aventstack.version>5.1.2</com.aventstack.version>
    <com.google.code.json.version>2.12.1</com.google.code.json.version>
    <org.jsoup.version>1.18.3</org.jsoup.version>
    <org.seleniumhq.selenium.version>4.37.0</org.seleniumhq.selenium.version>
    <io.github.bonigarcia.version>6.3.3</io.github.bonigarcia.version>
    <org.testng.version>7.11.0</org.testng.version>
    <com.squareup.okhttp3.version>4.9.1</com.squareup.okhttp3.version>
    <ch.qos.logback.version>1.5.16</ch.qos.logback.version>
    <!-- Versiones de plugins -->
    <maven.clean.plugin.version>3.5.0</maven.clean.plugin.version>
    <maven.compiler.plugin.version>3.15.0</maven.compiler.plugin.version>
    <maven.dependency.plugin.version>3.10.0</maven.dependency.plugin.version>
    <maven.deploy.plugin.version>3.1.4</maven.deploy.plugin.version>
    <maven.jar.plugin.version>3.5.0</maven.jar.plugin.version>
    <maven.source.plugin.version>3.4.0</maven.source.plugin.version>
    <maven.surefire.plugin.version>3.5.5</maven.surefire.plugin.version>
    <maven.pmd.plugin.version>3.28.0</maven.pmd.plugin.version>
    <pmdVersion>7.23.0</pmdVersion>
    <maven.checkstyle.plugin.version>3.6.0</maven.checkstyle.plugin.version>
    <checkstyleVersion>13.4.0</checkstyleVersion>
    <spotbugs-maven-plugin.version>4.9.8.3</spotbugs-maven-plugin.version>
    <jacoco-maven-plugin.version>0.8.14</jacoco-maven-plugin.version>
    <org.owasp.dependency-check-maven.version>12.2.1</org.owasp.dependency-check-maven.version>
    <flatten-maven-plugin.version>1.7.3</flatten-maven-plugin.version>
  </properties>
  <build>
    <pluginManagement>
      <plugins>
        <!-- plugins del core de maven (no tienen que implementarlos los hijos) -->
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-clean-plugin</artifactId>
          <version>${maven.clean.plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>${maven.compiler.plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-dependency-plugin</artifactId>
          <version>${maven.dependency.plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>${maven.deploy.plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-jar-plugin</artifactId>
          <version>${maven.jar.plugin.version}</version>
          <configuration>
            <archive>
              <addMavenDescriptor>false</addMavenDescriptor>
            </archive>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-source-plugin</artifactId>
          <version>${maven.source.plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>${maven.surefire.plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-pmd-plugin</artifactId>
          <version>${maven.pmd.plugin.version}</version>
          <dependencies>
            <dependency>
              <groupId>net.sourceforge.pmd</groupId>
              <artifactId>pmd-core</artifactId>
              <version>${pmdVersion}</version>
            </dependency>
            <dependency>
              <groupId>net.sourceforge.pmd</groupId>
              <artifactId>pmd-java</artifactId>
              <version>${pmdVersion}</version>
            </dependency>
            <dependency>
              <groupId>net.sourceforge.pmd</groupId>
              <artifactId>pmd-javascript</artifactId>
              <version>${pmdVersion}</version>
            </dependency>
            <dependency>
              <groupId>net.sourceforge.pmd</groupId>
              <artifactId>pmd-jsp</artifactId>
              <version>${pmdVersion}</version>
            </dependency>
          </dependencies>
          <configuration>
            <linkXRef>false</linkXRef>
            <verbose>true</verbose>
            <failOnViolation>true</failOnViolation>
            <includeTests>true</includeTests>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-checkstyle-plugin</artifactId>
          <version>${maven.checkstyle.plugin.version}</version>
          <dependencies>
            <dependency>
              <groupId>com.puppycrawl.tools</groupId>
              <artifactId>checkstyle</artifactId>
              <version>${checkstyleVersion}</version>
            </dependency>
          </dependencies>
          <configuration>
            <consoleOutput>true</consoleOutput>
            <includeTestSourceDirectory>true</includeTestSourceDirectory>
            <failsOnError>true</failsOnError>
            <failOnViolation>true</failOnViolation>
            <linkXRef>false</linkXRef>
            <configLocation>checkstyle_checks.xml</configLocation>
          </configuration>
        </plugin>
        <plugin>
          <groupId>com.github.spotbugs</groupId>
          <artifactId>spotbugs-maven-plugin</artifactId>
          <version>${spotbugs-maven-plugin.version}</version>
          <configuration>
            <includeTests>true</includeTests>
            <htmlOutput>true</htmlOutput>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.jacoco</groupId>
          <artifactId>jacoco-maven-plugin</artifactId>
          <version>${jacoco-maven-plugin.version}</version>
          <configuration>
            <excludes>
              <exclude>**/java_generated/**</exclude>
              <exclude>**/**generated**/**</exclude>
            </excludes>
          </configuration>
          <executions>
            <execution>
              <goals>
                <goal>prepare-agent</goal>
              </goals>
            </execution>
            <execution>
              <id>report</id>
              <phase>package</phase>
              <goals>
                <goal>report</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.owasp</groupId>
          <artifactId>dependency-check-maven</artifactId>
          <version>${org.owasp.dependency-check-maven.version}</version>
          <configuration>
            <nvdDatafeedServerId>DITI-3rdParty</nvdDatafeedServerId>
            <nvdDatafeedUrl>
              https://artifactory.mjusticia.es/artifactory/DITI-3rdParty/nvdcve/nvdcve/2.0/nvdcve-2.0-{0}.json.gz
            </nvdDatafeedUrl>
            <retireJsUrl>https://artifactory.mjusticia.es/artifactory/DITI-3rdParty/nvdcve/nvdcve/jsrepository/nvdcve-jsrepository.json</retireJsUrl>
            <retireJsUrlServerId>DITI-3rdParty</retireJsUrlServerId>
            <ossindexAnalyzerEnabled>false</ossindexAnalyzerEnabled>
            <knownExploitedEnabled>false</knownExploitedEnabled>
            <!-- Deshabilita el análisis de .NET -->
            <assemblyAnalyzerEnabled>false</assemblyAnalyzerEnabled>
            <formats>
              <format>XML</format>
              <format>JSON</format>
              <format>HTML</format>
            </formats>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <!-- Mete el valor de ${revision} en el pom -->       
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>flatten-maven-plugin</artifactId>
        <version>${flatten-maven-plugin.version}</version>
        <configuration>
          <updatePomFile>true</updatePomFile>
          <flattenMode>resolveCiFriendliesOnly</flattenMode>
        </configuration>
        <executions>
          <execution>
            <id>flatten</id>
            <phase>process-resources</phase>
            <goals>
              <goal>flatten</goal>
            </goals>
          </execution>
          <execution>
            <id>flatten.clean</id>
            <phase>clean</phase>
            <goals>
              <goal>clean</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>