package es.mjusticia.pagojus.frontconsola.model.vo.forms;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/*-
 * #%L
 * pagojus-restws
 * %%
 * Copyright (C) 2023 - 2024 Ministerio de la Presidencia, Justicia y Relaciones con las Cortes
 * %%
 * Licencia con arreglo a la EUPL, Versión 1.2 o –en cuanto
 *  sean aprobadas por la Comisión Europea– versiones
 *  posteriores de la EUPL (la «Licencia»)
 *  Solo podrá usarse esta obra si se respeta la Licencia.
 *  Puede obtenerse una copia de la Licencia en:
 * 
 *  https://joinup.ec.europa.eu/software/page/eupl
 * 
 *  Salvo cuando lo exija la legislación aplicable o se acuerde
 *  por escrito, el programa distribuido con arreglo a la
 *  Licencia se distribuye «TAL CUAL»,
 *  SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, ni expresas
 *  ni implícitas.
 *  Véase la Licencia en el idioma concreto que rige
 *  los permisos y limitaciones que establece la Licencia
 * #L%
 */

/**
 * Tasas generated by hbm2java
 */

public class ConsolaEditarFormVO {

  private String nrc;

  private String expediente;

  private String estadoTasa;

  private String idPago;

  private String idLocalizador;

  private String codTasa;

  private String descTasa;

  private String importe;

  private String documentoPagador;

  private String documentoRepresentante;

  private String nombreCompletoRepresentante;

  private String importeTasa;

  private String fhPago;

  private String nombreCompleto;

  private String codAplicacion;

  private int contadorHistorialVolver;

  public String getNrc() {
    return nrc;
  }

  public void setNrc(String nrc) {
    this.nrc = nrc;
  }

  public String getExpediente() {
    return expediente;
  }

  public void setExpediente(String expediente) {
    this.expediente = expediente;
  }

  public String getEstadoTasa() {
    return estadoTasa;
  }

  public void setEstadoTasa(String estadoTasa) {
    this.estadoTasa = estadoTasa;
  }

  public String getIdPago() {
    return idPago;
  }

  public void setIdPago(String idPago) {
    this.idPago = idPago;
  }

  public String getIdLocalizador() {
    return idLocalizador;
  }

  public void setIdLocalizador(String idLocalizador) {
    this.idLocalizador = idLocalizador;
  }

  public String getCodTasa() {
    return codTasa;
  }

  public void setCodTasa(String codTasa) {
    this.codTasa = codTasa;
  }

  public String getDescTasa() {
    return descTasa;
  }

  public void setDescTasa(String descTasa) {
    this.descTasa = descTasa;
  }

  public String getImporte() {
    return importe;
  }

  public void setImporte(String importe) {
    this.importe = importe;
  }

  public String getDocumentoPagador() {
    return documentoPagador;
  }

  public void setDocumentoPagador(String documentoPagador) {
    this.documentoPagador = documentoPagador;
  }

  public String getDocumentoRepresentante() {
    return documentoRepresentante;
  }

  public void setDocumentoRepresentante(String documentoRepresentante) {
    this.documentoRepresentante = documentoRepresentante;
  }

  public String getNombreCompletoRepresentante() {
    return nombreCompletoRepresentante;
  }

  public void setNombreCompletoRepresentante(String nombreCompletoRepresentante) {
    this.nombreCompletoRepresentante = nombreCompletoRepresentante;
  }

  public String getImporteTasa() {
    return importeTasa;
  }

  public void setImporteTas(String importeTasa) {
    this.importeTasa = importeTasa;
  }

  public String getFhPago() {
    return fhPago;
  }

  public void setFhPago(String fhPago) {
    this.fhPago = fhPago;
  }

  public String getNombreCompleto() {
    return nombreCompleto;
  }

  public void setNombreCompleto(String nombreCompleto) {
    this.nombreCompleto = nombreCompleto;
  }

  public String getCodAplicacion() {
    return codAplicacion;
  }

  public void setCodAplicacion(String codAplicacion) {
    this.codAplicacion = codAplicacion;
  }

  public int getContadorHistorialVolver() {
    return contadorHistorialVolver;
  }

  public void setContadorHistorialVolver(int contadorHistorialVolver) {
    this.contadorHistorialVolver = contadorHistorialVolver;
  }
}
