package es.mjusticia.pagojus.frontconsola.model.vo.forms;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/*-
 * #%L
 * pagojus-restws
 * %%
 * Copyright (C) 2023 - 2024 Ministerio de la Presidencia, Justicia y Relaciones con las Cortes
 * %%
 * Licencia con arreglo a la EUPL, Versión 1.2 o –en cuanto
 *  sean aprobadas por la Comisión Europea– versiones
 *  posteriores de la EUPL (la «Licencia»)
 *  Solo podrá usarse esta obra si se respeta la Licencia.
 *  Puede obtenerse una copia de la Licencia en:
 * 
 *  https://joinup.ec.europa.eu/software/page/eupl
 * 
 *  Salvo cuando lo exija la legislación aplicable o se acuerde
 *  por escrito, el programa distribuido con arreglo a la
 *  Licencia se distribuye «TAL CUAL»,
 *  SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, ni expresas
 *  ni implícitas.
 *  Véase la Licencia en el idioma concreto que rige
 *  los permisos y limitaciones que establece la Licencia
 * #L%
 */

/**
 * Tasas generated by hbm2java
 */

public class ConsolaPrincipalFormVO {

  private String filtroIdTasa;
  private String filtroLocalizador;
  private String filtroNombreTasa;
  private String filtroNRC;
  private String fechaPagoDesde;
  private String fechaPagoHasta;
  private String filtroNombrePagador;
  private String filtroApellido1Pagador;
  private String filtroApellido2Pagador;
  private String filtroDocumentoPagador;
  private String filtroNombreEntidad;
  private String filtroApellido1Entidad;
  private String filtroApellido2Entidad;
  private String filtroDocumentoEntidad;
  private String filtroRazonSocial;
  private String filtroEstadoTasa;

  /*
   * public void postProcesamiento() { listaTasas.clear();
   * 
   * String[] tasasUnidades = codigoTasas.split("\\."); for (String tasaUnidad :
   * tasasUnidades) { String[] tasaUnidadSep = tasaUnidad.split("-");
   * 
   * for (int i = 0; i < Integer.parseInt(tasaUnidadSep[1]); i++) {
   * listaTasas.add(tasaUnidadSep[0]); } }
   * 
   * tasasUnicas = new HashSet<>(listaTasas); }
   * 
   * public String getCodigoTasas() { return codigoTasas; }
   */

  public String getFiltroIdTasa() {
    return filtroIdTasa;
  }

  public void setFiltroIdTasa(String filtroIdTasa) {
    this.filtroIdTasa = filtroIdTasa;
  }

  public String getFiltroLocalizador() {
    return filtroLocalizador;
  }

  public void setFiltroLocalizador(String filtroLocalizador) {
    this.filtroLocalizador = filtroLocalizador;
  }

  public String getFiltroNombreTasa() {
    return filtroNombreTasa;
  }

  public void setFiltroNombreTasa(String filtroNombreTasa) {
    this.filtroNombreTasa = filtroNombreTasa;
  }

  public String getFiltroNRC() {
    return filtroNRC;
  }

  public void setFiltroNRC(String filtroNRC) {
    this.filtroNRC = filtroNRC;
  }

  public String getFechaPagoDesde() {
    return fechaPagoDesde;
  }

  public void setFechaPagoDesde(String fechaPagoDesde) {
    this.fechaPagoDesde = fechaPagoDesde;
  }

  public String getFechaPagoHasta() {
    return fechaPagoHasta;
  }

  public void setFechaPagoHasta(String fechaPagoHasta) {
    this.fechaPagoHasta = fechaPagoHasta;
  }

  public String getFiltroNombrePagador() {
    return filtroNombrePagador;
  }

  public void setFiltroNombrePagador(String filtroNombrePagador) {
    this.filtroNombrePagador = filtroNombrePagador;
  }

  public String getFiltroApellido1Pagador() {
    return filtroApellido1Pagador;
  }

  public void setFiltroApellido1Pagador(String filtroApellido1Pagador) {
    this.filtroApellido1Pagador = filtroApellido1Pagador;
  }

  public String getFiltroApellido2Pagador() {
    return filtroApellido2Pagador;
  }

  public void setFiltroApellido2Pagador(String filtroApellido2Pagador) {
    this.filtroApellido2Pagador = filtroApellido2Pagador;
  }

  public String getFiltroDocumentoPagador() {
    return filtroDocumentoPagador;
  }

  public void setFiltroDocumentoPagador(String filtroDocumentoPagador) {
    this.filtroDocumentoPagador = filtroDocumentoPagador;
  }

  public String getFiltroNombreEntidad() {
    return filtroNombreEntidad;
  }

  public void setFiltroNombreEntidad(String filtroNombreEntidad) {
    this.filtroNombreEntidad = filtroNombreEntidad;
  }

  public String getFiltroApellido1Entidad() {
    return filtroApellido1Entidad;
  }

  public void setFiltroApellido1Entidad(String filtroApellido1Entidad) {
    this.filtroApellido1Entidad = filtroApellido1Entidad;
  }

  public String getFiltroApellido2Entidad() {
    return filtroApellido2Entidad;
  }

  public void setFiltroApellido2Entidad(String filtroApellido2Entidad) {
    this.filtroApellido2Entidad = filtroApellido2Entidad;
  }

  public String getFiltroDocumentoEntidad() {
    return filtroDocumentoEntidad;
  }

  public void setFiltroDocumentoEntidad(String filtroDocumentoEntidad) {
    this.filtroDocumentoEntidad = filtroDocumentoEntidad;
  }

  public String getFiltroRazonSocial() {
    return filtroRazonSocial;
  }

  public void setFiltroRazonSocial(String filtroRazonSocial) {
    this.filtroRazonSocial = filtroRazonSocial;
  }

  public String getFiltroEstadoTasa() {
    return filtroEstadoTasa;
  }

  public void setFiltroEstadoTasa(String filtroEstadoTasa) {
    this.filtroEstadoTasa = filtroEstadoTasa;
  }

}
