<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>es.mjusticia.corium</groupId>
    <artifactId>corium-root</artifactId>
    <version>${revision}</version>
  </parent>
  <artifactId>corium-starters</artifactId>
  <version>${revision}</version>
  <packaging>pom</packaging>
  <modules>
    <module>corium-selenium-starter</module>
    <module>corium-playwright-starter</module>
  </modules>
</project>
